server:
  port: 8401

spring:
  application:
    name: alibaba-cloud-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080  #sentinel 监控8401微服务
        port: 8719  #默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口

#暴露，用于监控等
management:
  endpoints:
    web:
      exposure:
        include: '*'

