server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样率 1为全部采集

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用 负载均衡
    fetch-registry: true
    service-url:
      defaultZone:  http://127.0.0.1:7001/eureka/
  instance:
    instance-id: zipkin-sleuth-payment8001 #修改主机名称
    prefer-ip-address: true  #链接显示端口

