###服务端口号
server:
  port: 7001
###eureka 基本信息配置
spring:
  application:
    name: openfeign-eureka-server-7001
eureka:
  instance:
    ###注册到eureka ip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7002/eureka/   # 将本中心注册到指定中心上
      ###需要将我的服务注册到注册中心
      register-with-eureka: true
      ###是否需要从eureka上获取注册信息（需要检索服务）
      fetch-registry: true

  server:
    #关闭自我保护机制，保证不可用服务及时剔除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000


