server:
  port: 8403

spring:
  application:
    name: alibaba-sentinel-persist-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        port: 8719
      datasource: # 配置sentinel持久地址
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: alibaba-sentinel-persist-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'






