server:
  port: 8002

spring:
  application:
    name: gateway-cloud-eureka-payment-service
    devtools:
      restart:
        enabled: true  #设置开启热部署
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql驱动包
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用 负载均衡
    fetch-registry: true
    service-url:
      defaultZone:  http://127.0.0.1:7001/eureka/,http://127.0.0.1:7002/eureka  # 集群版
  instance:
    instance-id: payment8002 #修改主机名称
    prefer-ip-address: true  #链接显示端口
